### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'approach'

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#11]
When I ran `A_pairwise.py` in the `train_rel` folder, the following errors were shown, could you please help?
```
Traceback (most recent call last):
  File "A_pairwise.py", line 55, in <module>
    train_df = convert(t_df)
  File "A_pairwise.py", line 46, in convert
    ls.append([int(arr[i, 0]), int(arr[i, 1]),
ValueError: invalid literal for int() with base 10: 'approach'
```

By the way, at the correct repo. I think the `test1` folder should rename to `predict1` folder and override its content. I am afraid that it was due to an unintended commit.

**Comment by Liu-Hy** [comment]
Yes, <code>test1</code> is redundant. Thanks for pointing it out. It's helpful to report bugs even if you fixed them easily.
I changed line 46 to be <code>ls.append([int(arr[i, 0]), arr[i, 1], ...</code> and now it should work.
Note that <code>A_pairwise.py</code> just works as a baseline to the alternative scheme, so the models trained with this script are not used in prediction.

**Comment by GabrielLin** [comment]
Thank you for fixing it. The more descriptive documents you added this time are very helpful.
