### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#13]
When I ran `predict_triples.py` in the `predict1` folder, the following errors were shown, could you please help?
```
Traceback (most recent call last):
  File "predict_triples.py", line 199, in <module>
    data=pd.DataFrame(data,columns=['triple_'+lt[i]])
IndexError: list index out of range
```
I am afraid that this issue is caused by using `i` in both line 177 and line 195. `predict2` and `predict3` have the same situations.

**Comment by Liu-Hy** [comment]
Thanks for reporting. 'i' should be replaced. I have fixed the bug.

**Comment by GabrielLin** [comment]
Thank you for fixing the issue. I can use the script to generate triples now but having some empty result lines such as 
```
3671,,,,,[],[],,,,,
3672,,,,,[],[],,,,,
3673,,,,,[],[],,,,,
3674,,,,,[],[],,,,,
3675,,,,,[],[],,,,,
```
I will rerun the whole project with your latest commit and check whether the output appears again or not.  The issue is closed.

**Comment by Liu-Hy** [comment]
The empty lines are due to some problem in the predict_triples.py. I didn't find it in my recent updates. I'll try to fix it.

**Comment by GabrielLin** [comment]
Got it with thanks.
