### ISSUE TITLE
Ensembling Models

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#14]
It seems that the technology of Ensembling Models is not used in `predict1` and not used in the classification of contribution sentences. Are there any special reasons? Thanks.

**Comment by Liu-Hy** [comment]
The main reason was that we were in a hurry to write the prediction scripts, and didn't have time to ensemble in Phase 1. The computational budget is another concern. This repo only presents what we did. Ensemble would presumably improve the result in all subtasks.

**Comment by GabrielLin** [comment]
Got it with thanks. Even you did not use it in all parts but you are still the No. 1, haha.
