### ISSUE TITLE
Commit on Aug 4, 2021

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#15]
I found two new commits on Aug 4, 2021. Some modifications were made to the predict code. Are those commits affect the results? Could you descript more about the modifications of predict parts? Thanks.

**Comment by Liu-Hy** [comment]
I made some minor modifications like changing the logging level so that "0 accuracy" won't be shown during prediction, removing redundant operations in dataframes, and adding comments. I verified that the script can run, and the results were not changed.

**Comment by GabrielLin** [comment]
Got it with thanks. What a fast reply!
