### ISSUE TITLE
Related papers

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#8]
Is there any related paper to this repo? Thanks.

**Comment by Liu-Hy** [comment]
I have posted our paper, "UIUC_BioNLP at SemEval-2021 Task 11: A Cascade of Neural Models for Structuring Scholarly NLP Contributions" to arXiv, which will be available soon. Sorry that I haven't got time to clean the code, which is a bit messy. I'll do that in two weeks.

**Comment by GabrielLin** [comment]
I am looking forward to it. Thanks.

**Comment by Liu-Hy** [comment]
I have re-organized the code. Some debugging needs to be done later, but it is generally fine.

**Comment by GabrielLin** [comment]
Sorry, I missed the notification. Got it. Thanks.
