### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 60: invalid start byte

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#9]
When I run `pre.py` in the `test1` folder. The following errors are shown. Could you help? Thanks.
```
Traceback (most recent call last):
  File "pre.py", line 209, in <module>
    data = load_data_sentence(file_path)
  File "pre.py", line 203, in load_data_sentence
    paper_data = load_paper_sentence(sentence_path)
  File "pre.py", line 121, in load_paper_sentence
    fl = f.readlines()
  File "/home/XXXX/.conda/envs/py36liuhy/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 60: invalid start byte

```

**Comment by Liu-Hy** [comment]
Thanks for the report. Strange that I ran the script but did not meet this problem. You can try modifying line 120 of <code>pre.py</code> in this order:

1) with open(ocr_path, 'rb') as f:
2) with open(ocr_path, 'r', encoding='utf-8') as f:
3) with open(ocr_path, 'r', encoding='rgb') as f:

Please let me know if the problem persists.

**Comment by GabrielLin** [comment]
Thank you @Liu-Hy . It works after changing to option 1. Actually, I have tried to change to option 2 before I created the issues.
